platform :ios, '6.0'

# ignore all warnings from cocoa pods
inhibit_all_warnings!

pod 'XtifyLib', :git => 'https://github.com/sstepashka/XtifyLib.git', :branch => 'master'

post_install do |installer|
    config = <<-XTIFYGLOBAL_H
#define xAppKey @"123123"
#define xLocationRequired NO
#define xRunAlsoInBackground FALSE
#define xDesiredLocationAccuracy kCLLocationAccuracyKilometer  // kCLLocationAccuracyBest
#define xBadgeManagerMethod XLInboxManagedMethod
#define xLogging TRUE
#define xMultipleMarkets FALSE
XTIFYGLOBAL_H
    File.open("Pods/XtifyLib/XtifyLib/XtifyGlobal.h", "w") do |file|
      file.puts config
    end
end
